export type CourseLesson = {
  id: string;
  n: string;
  title: string;
  ru: string;
  pages: string;
  cd: 1 | 2 | 3;
  tracks: string[];
  objective: string;
  pictureWords: string[];
  words: [string, string][];
  phrases: string[];
  radioFocus: string;
  time: number;
  level: "ICAO 4";
};

const L = (
  n: number, title: string, ru: string, pages: string, cd: 1 | 2 | 3,
  tracks: string[], objective: string, pictureWords: string[],
  words: [string, string][], phrases: string[], radioFocus: string,
): CourseLesson => ({ id: `${n}-${title.toLowerCase().replace(/[^a-z]+/g, "-").replace(/-$/, "")}`, n: String(n).padStart(2, "0"), title, ru, pages, cd, tracks, objective, pictureWords, words, phrases, radioFocus, time: tracks.length > 3 ? 28 : 22, level: "ICAO 4" });

export const lessons: CourseLesson[] = [
  L(1,"Near miss","Опасное сближение","8-9",1,["01","02","03"],"Описать опасное сближение, восстановить последовательность событий и запросить уточнение.",["angle","starboard","twin","smaller","tail","obscured"],[["airprox","опасное сближение"],["distance","расстояние"],["potential","потенциальный риск"],["abort","прервать"],["deviate","отклониться"],["close","близкий"],["collision","столкновение"],["risk","риск"]],["Say again the squawk.","Traffic avoiding action.","We have people injured."],"Avoiding action, TCAS RA и срочный запрос снижения"),
  L(2,"Special flights","Особые полёты","10-11",1,["04","05","06"],"Сравнить IFR/VFR движение и объяснить нестандартное построение схемы.",["vintage","formation","smoke trail","aircraft markings","aerobatic","manoeuvre"],[["air show","авиашоу"],["bi-plane","биплан"],["twin-engine","двухдвигательный"],["low-wing","низкоплан"],["amphibious","амфибийный"],["floatplane","гидросамолёт"],["high-wing","высокоплан"],["routine","порядок действий"]],["I can see the high-wing aircraft.","Keep it up until west of the field.","Turn left and get in line."],"Sequencing необычных типов воздушных судов на авиашоу"),
  L(3,"VIP flights","VIP-полёты","12-13",1,["07","08","09"],"Объяснить влияние VIP-движения на задержки, приоритет и запас топлива.",["dispersal","air stair","APU","palm","baggage","visibility"],[["priority","приоритет"],["amendment","изменение"],["officials","официальные лица"],["panic","паниковать"],["domestic","внутренний"],["facilities","средства обслуживания"],["disruption","нарушение работы"],["scheduled","регулярный, по расписанию"]],["Confirm we have to hold.","We did not get that information.","We may have to use our alternate."],"NOTAM, holding и решение об уходе на запасной"),
  L(4,"Delays","Задержки","14-15",1,["10","11","12","13","14","15","16"],"Определять причины задержек и точно сообщать ожидаемую продолжительность.",["commercial","sequence","instrument","configuration","final","radar"],[["disable","вывести из строя"],["work","работы"],["spillage","разлив"],["removal","удаление"],["issue","проблема"],["saturation","перегрузка сектора"],["regulation","ограничение"],["exercise","учения"]],["Disabled aircraft on the runway.","Remain outside controlled airspace.","Do you have an estimate?"],"Пять диалогов о задержке: полоса, видимость, стоянка, насыщение"),
  L(5,"Belly-landings","Посадка без шасси","16-17",1,["17","18","19"],"Сообщить о небезопасной индикации шасси и запросить визуальную проверку.",["medium","emblem","gear","standing","propeller","horizon"],[["collapse","сложиться"],["bent","погнутый"],["skid","скользить"],["lower","выпустить, опустить"],["circuit","круг полётов"],["indication","индикация"],["appear","выглядеть"],["undercarriage","шасси"]],["Unsafe main gear indication.","Request low pass to confirm.","All wheels appear down."],"Low pass, визуальная проверка и abnormal gear landing"),
  L(6,"Birds","Птицы","20-21",1,["23","24","25"],"Описать bird strike, повреждение и ожидаемые проблемы с управлением.",["military","high-wing","turboprop","dip","flock","frightened"],[["detect","обнаружить"],["corridor","коридор"],["track","отслеживать"],["flock","стая"],["species","вид"],["hit","ударить"],["impact","удар"],["frighten","испугать"]],["We had an impact with the nose gear.","We still have a red light.","We may have steering problems."],"Bird strike, low pass и приоритетная посадка"),
  L(7,"Cargo","Грузовые перевозки","22-23",1,["26","27","28"],"Объяснить загрузку груза, повреждение панели и необходимость инженерной проверки.",["lined up","terminal","containers","vehicles","pallets"],[["piece","предмет, часть"],["pallet","поддон"],["label","маркировка"],["load","загружать"],["protect","защищать"],["wrap","оборачивать"],["band","крепёжная лента"],["panel","панель"]],["Do you have contact with an engineer?","We are not sure if it is closed.","Confirm the warning light is extinguished."],"Незакрытая панель, связь с dispatch и engineer"),
  L(8,"On-board fire","Пожар на борту","24-25",1,["29","30","31"],"Сообщить о пожаре в салоне, применении огнетушителя и плане эвакуации.",["training exercise","mock-up","engulfed","flames","firefighters","spray"],[["appliance","пожарный автомобиль"],["foam","пена"],["mounted","установленный"],["monitor","лафетный ствол"],["media","огнетушащее средство"],["deploy","применить"],["halon","хладон"],["hose","рукав"]],["Confirm the fire is in the lavatory.","We will continue the Mayday call.","We will make a complete stop."],"Mayday, cabin fire, landing и secure area"),
  L(9,"Ground movement incidents","Инциденты на земле","26-27",1,["32","33","34"],"Уточнять стоянку, следовать follow-me и сообщать о столкновении при рулении.",["stripes","follow-me lights","line","cables","holding"],[["follow","следовать"],["fence","ограждение"],["sign","знак"],["marshaller","сигнальщик"],["van","фургон"],["truck","грузовик"],["camouflage","камуфляж"],["narrow","узкий"]],["Confirm we are at stand 116.","We have the marshaller in sight.","We hit the drainage ditch."],"Неверная стоянка, green lights и препятствие"),
  L(10,"Pilot incapacitation","Недееспособность пилота","28-29",1,["35","36","37"],"Объяснить состояние пилота и запросить немедленное содействие и diversion.",["patient","ambulance","stretcher","suit","mask","nurse"],[["incapacitated","недееспособный"],["cramp","судорога"],["vomit","рвать"],["tighten","напрягаться"],["short","нехватка"],["poisoning","отравление"],["pass out","потерять сознание"],["nauseous","испытывающий тошноту"]],["The pilot has passed out.","I am on my own up here.","Can you get fresh air into the cabin?"],"Incapacitated pilot, diversion и медицинская помощь"),
  L(11,"Ditchings","Приводнение","32-33",1,["43","44","45"],"Сообщить о потере двигателей, выборе места приводнения и доступных спасательных средствах.",["wreck","fuselage","registration","submerged","split","broken"],[["flotation","плавучесть"],["inflatable","надувной"],["boat","лодка"],["ship","судно"],["lake","озеро"],["coast","побережье"],["impact","удариться"],["procedure","процедура"]],["We may lose both engines.","We are not able to reach land.","Brief the cabin crew and passengers."],"Ditching, POB, coastguard и rescue helicopter"),
  L(12,"Animals","Животные","34-35",1,["46","47","48","49","50"],"Описать животных на ВПП, прервать взлёт и запросить удаление препятствия.",["plain","grass airstrip","remote","mammal","ridge","wild"],[["live","живой"],["hazard","опасность"],["wildlife","дикие животные"],["run around","бегать"],["secure","обезопасить"],["dead","мёртвый"],["roam","бродить"],["rodent","грызун"]],["There is wildlife in front of us.","They are heading towards the grass.","Send someone out to remove it."],"Animals near arriving and departing traffic"),
  L(13,"Wind and turbulence","Ветер и турбулентность","36-37",2,["01","02","03"],"Объяснить wake turbulence, windshear и варианты обхода опасной погоды.",["unstable","low","wheel","smoke","nose","grass"],[["unconventional","нестандартный"],["separation","эшелонирование"],["anticipate","предвидеть"],["bumpy","болтаночный"],["displace","смещать"],["unstable","нестабильный"],["touch","касаться"],["trailing","следующий позади"]],["The weather appears to be moving south.","What heading do you want?","Keep us informed."],"Wake turbulence, microburst и delaying vectors"),
  L(14,"Icing","Обледенение","38-39",2,["04","05","06"],"Распознать severe icing, потерю скорости и запросить изменение высоты или маршрута.",["departure","mountainous","spray","fluid","melt","de-icing facility"],[["boot","пневмообледенитель"],["freeze up","замёрзнуть"],["pick up","набирать"],["build up","нарастать"],["heat","обогрев"],["melt","таять"],["vibrate","вибрировать"],["accumulate","накапливаться"]],["I am getting some control now.","Your pitot tube may be frozen.","You might pick up more icing."],"Uncontrolled descent и отказ airspeed indication"),
  L(15,"Storms","Грозы","40-41",2,["07","08","09","10","11","12"],"Сообщать о lightning strike, windshear, CB и необходимости немедленного обхода.",["dark","convective","storm","fork lightning","water","distance"],[["updraft","восходящий поток"],["jolt","резкий толчок"],["strike","удар"],["cell","грозовая ячейка"],["through","сквозь"],["around","вокруг"],["into","внутрь"],["circumnavigate","обойти"]],["We think we had a lightning strike.","Request higher for weather avoidance.","We would like to divert for inspection."],"Четыре диалога: windshear, lightning, turbulence и CB"),
  L(16,"Depressurization","Разгерметизация","44-45",2,["16","17","18"],"Сообщить о разгерметизации, аварийном снижении и повреждении фюзеляжа.",["top","failure","damaged","structural","vehicle","section"],[["sabotage","саботаж"],["failure","отказ"],["structural","конструкционный"],["penetrate","пробить"],["rupture","разрыв"],["discharge","выброс"],["external","внешний"],["residue","остаток"]],["Your transmission is breaking up.","We cannot communicate with the cabin.","We need assistance for passengers."],"Emergency descent, связь на запасной частоте и landing"),
  L(17,"Passenger problems","Проблемы с пассажирами","46-47",2,["19","20","21"],"Описать unruly passenger, restraint, diversion и необходимые службы после посадки.",["concerned","malicious","headlock","strangle","wrestle","kneel"],[["yell","кричать"],["hurt","ранить"],["handcuff","надеть наручники"],["threaten","угрожать"],["alarm","тревога"],["hold down","удерживать"],["confront","противостоять"],["unarmed","безоружный"]],["We are looking for a diversion.","Five people are holding him down.","Coordinate with our operations."],"Unruly passenger, overweight landing и parking position"),
  L(18,"Bomb scare","Угроза взрыва","48-49",2,["22","23","24"],"Сообщить о подозрительном устройстве, угрозе и действиях security personnel.",["same","sign","machine","controlled","track","helmet"],[["suspicious","подозрительный"],["examine","осмотреть"],["disposal","обезвреживание"],["demand","требовать"],["armed","вооружённый"],["air marshal","воздушный маршал"],["restrain","обездвижить"],["overpower","скрутить"]],["We have a report of suspicious passengers.","The air marshals can overpower them.","The package has been restrained."],"Bomb threat, radar vector и security standing by"),
  L(19,"Take-off incidents","Инциденты на взлёте","50-51",2,["25","26","27","28","29"],"Описать tail strike, debris, fuel leak и решение о возврате.",["airborne","above","scrape","tail","surface","attitude"],[["leak","утечка"],["trail","след"],["material","материал"],["over","поверх"],["skin","обшивка"],["scrape","царапать"],["debris","обломки"],["abrasion","потёртость"]],["There is fuel on the taxiway.","We saw a leak from the wing.","Request return after a tail strike."],"FOD, fuel leak, missed approach и tail strike"),
  L(20,"Lost","Потеря ориентировки","52-53",2,["30","31","32"],"Сообщить о потере навигации и выполнить no-gyro surveillance approach.",["calm","vessel","reconnaissance","rescue","turn","lifeboat"],[["route","маршрут"],["rescue","спасать"],["chart","карта"],["align","совмещать"],["low","низко"],["seem","казаться"],["compass","компас"],["gyro","гироскоп"]],["Are you declaring a fuel emergency?","Can you vector us low enough?","This will be a no-gyro approach."],"Lost aircraft, last known position и radar vector"),
  L(21,"Aircraft breakdown - mechanical","Механическая неисправность","56-57",2,["36","37","38"],"Описать механический отказ, состояние шасси и потребность в maintenance.",["hangar","maintenance","cowling","intake","inspect","diagnostic"],[["mechanic","механик"],["release","допуск к полёту"],["inoperative","неисправный"],["refuse","отказаться"],["sort out","устранить"],["hangar","ангар"],["install","установить"],["MEL","перечень минимального оборудования"]],["Runway disabled due aircraft.","We need the landing gear pinned.","Is there maintenance on the field?"],"Disabled aircraft, disembarkation и towing assistance"),
  L(22,"Aircraft breakdown - electrical","Электрическая неисправность","58-59",2,["39","40","41"],"Объяснить electrical failure, потерю освещения и возможный diversion.",["engineer","instruments","internal","hand","tray","electronics"],[["delicate","чувствительный"],["alternator","генератор переменного тока"],["loose","ослабленный"],["generator","генератор"],["output","выходная мощность"],["charge","заряжать"],["strobe","стробоскоп"],["wire","провод"]],["I think I can see you on radar.","I will try to turn the lights on.","There is no known traffic conflict."],"Backup power, transponder и видимость воздушного судна"),
  L(23,"Volcanoes","Вулканы","60-61",2,["42","43","44"],"Сообщить о вулканическом пепле, видимости и предполагаемом движении облака.",["active","erupting","plume","ash","steam","cloud"],[["smell","запах"],["haze","дымка"],["fall","выпадение"],["conical","конический"],["crater","кратер"],["rim","край"],["lava","лава"],["slope","склон"]],["Any reports of volcanic ash?","Say position where you encountered it.","Direction of cloud movement is unknown."],"PIREP об ash cloud, climb и deterioration of visibility"),
  L(24,"Dangerous goods","Опасные грузы","62-63",3,["01","02","03"],"Распознать dangerous goods, fumes и подготовить срочную посадку.",["flammable","explosive","fireworks","matches","torch","canister"],[["forbidden","запрещённый"],["symbol","символ"],["hold","грузовой отсек"],["floor","пол"],["substance","вещество"],["precaution","мера предосторожности"],["handler","грузчик"],["stack","складывать"]],["We have fumes in the cabin.","It is starting to hurt my eyes.","We will be on the ground soon."],"Fumes, vents, overhead lockers и immediate evacuation"),
  L(25,"Collisions","Столкновения","64-65",3,["04","05","06"],"Описать наземное столкновение и запросить осмотр повреждений.",["collide","lodge","trailing edge","slice","empennage","floodlit"],[["stationary","неподвижный"],["clip","задеть"],["lodge","застрять"],["strike","ударить"],["slice","разрезать"],["underside","нижняя поверхность"],["contact","контакт"],["tip","законцовка"]],["There will be backtracking traffic.","The Piper brushed our wing tip.","Request permission to leave the aircraft."],"Opposite-direction traffic, collision и inspection"),
  L(26,"Fuel problems","Проблемы с топливом","68-69",3,["10","11","12"],"Сообщить об утечке, imbalance, fuel dump и минимальном остатке.",["refuelled","hillside","underground","vehicle","clothing","wing"],[["leak","утечка"],["tank","бак"],["pump","перекачивать"],["line","трубопровод"],["refuel","заправлять"],["unserviceable","непригодный"],["recurring","повторяющийся"],["block","засорить"]],["We are deciding whether to return.","It looks like we have to dump fuel.","I will give you vectors on completion."],"Low fuel, dump, flap restriction и diversion"),
  L(27,"Airfield activities","Деятельность на аэродроме","70-71",3,["13","14","15","16","17","18"],"Сообщить о balloon, paraglider, protesters и work in progress.",["playing field","formation","demonstrators","residential area","industrial","warehouses"],[["protest","протестовать"],["investigation","расследование"],["converge","сходиться"],["breach","нарушение периметра"],["break through","прорваться"],["fencing","ограждение"],["occupy","занять"],["climb","перелезть"]],["Request permission to hold.","Caution, work in progress ahead.","People are at the western perimeter."],"Balloon, vehicles, protesters и unidentified activity"),
  L(28,"Aerodrome/airfield environment","Аэродромная среда","72-73",3,["19","20","21"],"Описать сложный аэродром, displaced threshold и конфликт маршрутов.",["strip","houses","mountain","twin","valley","overshoot"],[["extended","продолженный"],["marshaller","сигнальщик"],["overshoot","перелететь"],["dust","пыль"],["basin","котловина"],["plateau","плато"],["hover","висеть"],["corridor","коридор"]],["You are too close to the extended centreline.","Stay on the western side.","Hold in the hover south of the runway."],"Convoy crossing, helicopter hover и confined approach"),
  L(29,"Airfield and navigation equipment failure","Отказ аэродромного и навигационного оборудования","74-75",3,["22","23","24","25","26","27"],"Распознать ошибочную индикацию, отказ огней или навигационного средства.",["extinguish","fire damage","blackened","explosion","evacuate","firefighting"],[["lose","потерять"],["fail","отказать"],["ignore","игнорировать"],["unserviceable","неработоспособный"],["erroneous","ошибочный"],["faulty","неисправный"],["trust","доверять"],["concentrate","сосредоточиться"]],["Return to previously assigned headings.","The return may be erroneous.","We cannot see the runway lights."],"Radar malfunction, lighting failure и raw-data navigation"),
  L(30,"Ground services","Наземные службы","76-77",3,["28","29","30"],"Сообщить о vehicle incursion, столкновении и необходимости остановить двигатели.",["bent","dent","smashed","debris","twisted","force"],[["swerve","резко повернуть"],["axle","ось"],["digger","экскаватор"],["intersection","пересечение"],["construction","строительство"],["park","припарковать"],["cut","выключить"],["idle","малый газ"]],["Do you see anything near Korean Air?","We are looking at the right side.","Maybe it hit the outboard engine."],"Runway incursion, follow-up aircraft и emergency vehicle inspection"),
];

export type CourseTest = { id: string; title: string; scope: string; pages: string; cd: 1 | 2 | 3; tracks: string[] };

export const courseTests: CourseTest[] = [
  {id:"progress-1",title:"Progress test 1",scope:"Units 1-5",pages:"18-19",cd:1,tracks:["20","21","22"]},
  {id:"progress-2",title:"Progress test 2",scope:"Units 6-10",pages:"30-31",cd:1,tracks:["38","39","40","41","42"]},
  {id:"progress-3",title:"Progress test 3",scope:"Units 11-15",pages:"42-43",cd:2,tracks:["13","14","15"]},
  {id:"progress-4",title:"Progress test 4",scope:"Units 16-20",pages:"54-55",cd:2,tracks:["33","34","35"]},
  {id:"progress-5",title:"Progress test 5",scope:"Units 21-25",pages:"66-67",cd:3,tracks:["07","08","09"]},
  {id:"progress-6",title:"Progress test 6",scope:"Units 26-30",pages:"78-79",cd:3,tracks:["31","32","33","34","35"]},
  {id:"review-1",title:"Review test 1",scope:"Units 1-30",pages:"80-81",cd:3,tracks:["36","37","38"]},
  {id:"review-2",title:"Review test 2",scope:"Units 1-30",pages:"82-83",cd:3,tracks:["39","40","41"]},
];

export const audioSrc = (cd: number, track: string) => `/audio/CD${cd}/Track${track}.mp3`;
